title: Catalan news in English
logo: /assets/img/love_democracy.jpeg
description: If you have links to be added here let me know.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github.url: https://github.com/joanmarcriera/joanmarcriera.github.io
